import {NextPage} from "next";
import Head from "next/head";

const Start: NextPage = ()=>{
    return (
        <div>
            <Head>
                <title>Start of the game</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
        </div>
    )
}

export default Start;